apiVersion: v1 
kind: Service 
metadata: 
  name: frontend-service
spec: 
  selector: 
    app: frontend-app 
  ports: 
  - name: angular 
    targetPort: 80
    port: 80
  type: LoadBalancer
