apiVersion: v1
kind: Pod
metadata:
  name: frontend-backend-pod
  labels:
    app: frontend-backend
spec:
  containers:
  - name: angular-frontend
    image: swapnil0078/ang_frontend:angular
    ports:
    - containerPort: 80
      protocol: TCP
  - name: angular-backend
    image: swapnil0078/ang_backend:angular
    ports:
    - containerPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: frontend-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP