apiVersion: v1 
kind: Service 
metadata: 
  name: backend-service
spec: 
  selector: 
    app: backend-app 
  ports: 
  - name: tomcat 
    targetPort: 8080
    port: 8080
  type: ClusterIP
